# Generated by Django 3.2.9 on 2021-11-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=15)),
                ('version', models.CharField(max_length=15)),
                ('licensePlate', models.CharField(max_length=15)),
                ('km', models.CharField(max_length=15)),
                ('imgLink', models.CharField(max_length=999)),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
    ]
