# Generated by Django 3.2.9 on 2021-11-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_vehicle_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='km',
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='licensePlate',
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='version',
            field=models.CharField(max_length=999),
        ),
    ]
